### PR TITLE
Studio - Fix problems handling primitive numerical types in PropertyMap.

### PR DESCRIPTION
**Pull request by nicost**
Fix problems in handling primitive numericals types.  These changes
enable reading of at least some existing datasets.

### CODE REVIEW

**Comment by marktsuchida** [comment]
Thanks, @nicost. I pushed 5fd0bc3bf8e312a8ca22452c77e1de243c2d9fa3 which fixes `DefaultPropertyMap.getAsNumber()` without adding non-primitive types to the list of primitive types.
I'll now look into what to do with the other fix.

**Comment by marktsuchida** [comment]
Here's what I think needs to be done for the case of missing `MicroManagerVersion`:
- Make sure the JSON input in question is actually missing the MM version, as opposed to encoding it in some other way (which we should read)
- If yes (as I expect), then I would prefer to avoid introducing a special value ("0.0"), for which we will then need to check for everywhere (and eternally, if it ever makes its way into file data). Where is it that the `NullPointerException` is being thrown?

I'm a little confused because the method you changed is the one called for conversion of `PropertyMap` to JSON, as opposed to the other way around. It would help tremendously to understand why this is being done during a file read in the first place.

**Comment by nicost** [comment]
Funny, I can't seem to be able to find the file that caused this.  I have no idea about " the method you changed is the one called for conversion of PropertyMap to JSON, as opposed to the other way around", because the juggling that is going on with metadata is way too complicated for me to understand, I am simply trying to make things work. 

The only way forward I see is for you to create a whole bunch of files with older versions of MM  (both using MDA and scripts) and try to open them in mm2-next.  It is very time-consuming for me to go through this code, but mm2-next fails to open almost every other dataset, and does not release memory when closing them, so can not be used right now.  Instead of working on code, I'll open issues, and hopefully you will find time to fix these.

**Comment by nicost** [comment]
Ah!  No possibility to open issues on mark - micromanager ? How do you want to do this?  Here are two deal-breaking issues for starters:

- Dataset fails to open when no file names "Displaysettings.json" is present (which is the case for almost every dataset created by Micro-Manager.
- Memory is not released after closing the last viewer.  This causes the application to run out of available RAM very quickly.  Try opening and closing the same dataset multiple times.

**Comment by nicost** [comment]
Here is a dataset with missing Micro-Manager version : [http://valelab.ucsf.edu/~nico/images/noMMversion](http://valelab.ucsf.edu/~nico/images/noMMversion) .  May have come from a script, in any case, these files are out there.  Maybe it is simplest to set the version default to "Unknown"?

**Comment by marktsuchida** [comment]
@nicost I get a 404 from that link....

I would rather leave the version unset (or null) in all cases where we don't have a real version number, and fix any broken code that assumes the version exists. If we do it any other way, we end up with two special values that mean the same thing (`null` and `"Unknown"`), which means any correct code will need to check for both.

Re your earlier comments:

> mm2-next fails to open almost every other dataset, and does not release memory when closing them, so can not be used right now

I already know this. That's because `mm2-next` is a branch in which I have not yet (re-)implemented file I/O. Anything that is working is working by pure chance. File I/O is the next thing I need to fix in this branch, so info (like you are providing) on where it is broken and sample files are extremely helpful to have.

**Comment by nicost** [comment]
@marktsuchida 
> I get a 404 from that link....

Try again...

> I would rather leave the version unset (or null) in all cases where we don't have a real version number, and fix any broken code that assumes the version exists. If we do it any other way, we end up with two special values that mean the same thing (null and "Unknown"), which means any correct code will need to check for both.

Either way is fine with me.  There are certainly more cases where missing keys cause uncaught errors stopping data loading, so a more general method to deal with missing keys, or inspection of existing code is in order.

**Comment by marktsuchida** [comment]
@nicost thanks.

I did find and fix a few bugs related to keys missing in the property map representations, which would throw NPEs when trying to convert to JSON (6120a7388825982ec85088263816023227f3ffb5). One of them was `MicroManagerVersion`, so this might be related. Will see when my download of your dataset finishes....

**Pull request closed without merging**
